
package pe.company.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4
 * Thu Aug 04 21:16:32 COT 2022
 * Generated source version: 3.1.4
 */

@XmlRootElement(name = "listarClientesResponse", namespace = "http://ws.company.pe/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listarClientesResponse", namespace = "http://ws.company.pe/")

public class ListarClientesResponse {

    @XmlElement(name = "return")
    private java.util.List<pe.company.model.Cliente> _return;

    public java.util.List<pe.company.model.Cliente> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<pe.company.model.Cliente> new_return)  {
        this._return = new_return;
    }

}

