
package pe.company.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.4
 * Thu Aug 04 21:16:32 COT 2022
 * Generated source version: 3.1.4
 */

@XmlRootElement(name = "listarClientes", namespace = "http://ws.company.pe/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listarClientes", namespace = "http://ws.company.pe/")

public class ListarClientes {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

